# Generated by Django 5.0.3 on 2024-04-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0019_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert',
            field=models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3')], default='choice1', max_length=24),
        ),
    ]
