# Generated by Django 5.0.3 on 2024-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0020_alter_alert_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert',
            field=models.CharField(choices=[('sweetAlert', 'sweetAlert'), ('choice2', 'choice2')], default='sweetAlert', max_length=24),
        ),
    ]
